"""Added like and dislike counts

Revision ID: f42175a13a75
Revises: 
Create Date: 2023-11-15 04:33:28.844417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f42175a13a75'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.add_column(sa.Column('like_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('dislike_count', sa.Integer(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('picture',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=20),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('picture',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=256),
               nullable=True)

    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.drop_column('dislike_count')
        batch_op.drop_column('like_count')

    # ### end Alembic commands ###
